#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master


#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: src/Spk.Common.sln
  publish_nuget_symbols: true
  publish_nuget: true

version: 0.9.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

after_test:
  - ps: .\src\nuget\pack.ps1


#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**/*.Tests.Validators.dll'
    - '**/*.Tests.Helpers.dll'


#------------------------#
#       deployment       #
#------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: 08VoeMu7J5NvW2Rhro9kRtzP53d6omvavlOgBaY32/WQt5ENeE3HKKCe1tbCDOUy
  artifact: /.*\.nupkg/