image: Visual Studio 2017

branches:
  only:
    - master

install:
  - dotnet restore

build_script:
  - dotnet build -c Release

artifacts:
  - path: '**\*.nupkg'

test_script:
  - ps: gci -Directory -Path test | ForEach-Object {dotnet test -c Release $_.FullName}

deploy:
  provider: NuGet
  api_key:
    secure: 08VoeMu7J5NvW2Rhro9kRtzP53d6omvavlOgBaY32/WQt5ENeE3HKKCe1tbCDOUy
  artifact: /.*\.nupkg/