#---------------------------------#
#      general configuration      #
#---------------------------------#
image: Visual Studio 2017

branches:
  only:
    - master

configuration: Release

#---------------------------------#
#       build configuration       #
#---------------------------------#

install:
  - dotnet restore src

build:
  project: src/Spk.Common.sln
  publish_nuget_symbols: true
  publish_nuget: true

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - '**/*.Tests.*.dll'

#------------------------#
#       deployment       #
#------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: 08VoeMu7J5NvW2Rhro9kRtzP53d6omvavlOgBaY32/WQt5ENeE3HKKCe1tbCDOUy
  artifact: /.*\.nupkg/