#---------------------------------#
#      general configuration      #
#---------------------------------#
image: Visual Studio 2017

branches:
  only:
    - master

configuration: Release

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: src/Spk.Common.sln

#---------------------------------#
#       tests configuration       #
#---------------------------------#

#------------------------#
#       deployment       #
#------------------------#

deploy:
  provider: NuGet
  api_key:
    secure: 08VoeMu7J5NvW2Rhro9kRtzP53d6omvavlOgBaY32/WQt5ENeE3HKKCe1tbCDOUy
  artifact: /.*\.nupkg/